version: '2'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    container_name: blog-api
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    container_name: blog-db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo

